version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: php:custom
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
        - ./laravelSite:/var/www
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "4000:80"
      - "1000:443"
    volumes:
    - ./laravelSite:/var/www
    - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: laravel #This is your database name. You can Change it if you want. If you do change, update it in the .env file also
      MYSQL_ROOT_PASSWORD: password #This is your Root Password. You can Change it if you want. But keep track of this as it will be used in setting up the Containers
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
